image: Visual Studio 2017


environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  BOOST_VER: 1_69_0
  matrix:
# 32-bit
    - VCVARS: vcvarsamd64_x86
      VCPKG_PLATFORM: x86-windows
      # VCPKG_BOOST_PLATFORM: x86-windows-static
      
# 64-bit
    - VCVARS: vcvars64
      VCPKG_PLATFORM: x64-windows
      #VCPKG_BOOST_PLATFORM: x64-windows-static
      
cache:
  - c:\Tools\vcpkg\installed
  - c:\Tools\vcpkg\packages
  - c:\Tools\vcpkg\downloads

install:
  - git submodule update --init --recursive
  - choco install -y ninja
  # Add the libfunctionality port
  - ps: mkdir \tools\vcpkg\ports\libfunctionality
  - ps: iwr https://raw.githubusercontent.com/rpavlik/vcpkg/openxr/ports/libfunctionality/CONTROL -OutFile \tools\vcpkg\ports\libfunctionality\CONTROL
  - ps: iwr https://raw.githubusercontent.com/rpavlik/vcpkg/openxr/ports/libfunctionality/portfile.cmake -OutFile \tools\vcpkg\ports\libfunctionality\portfile.cmake
  - vcpkg install jsoncpp:%VCPKG_PLATFORM% opencv:%VCPKG_PLATFORM% libfunctionality:%VCPKG_PLATFORM% sdl2:%VCPKG_PLATFORM%
  # Grab a qedit header with an MIT license appended from an MS repo
  - ps: iwr https://raw.githubusercontent.com/microsoft/MixedRealityCompanionKit/master/SpectatorView/Compositor/CompositorDLL/qedit.h -OutFile \projects\qedit.h
  # - vcpkg install boost-algorithm:%VCPKG_BOOST_PLATFORM% boost-any:%VCPKG_BOOST_PLATFORM% boost-assert:%VCPKG_BOOST_PLATFORM% boost-chrono:%VCPKG_BOOST_PLATFORM% boost-date-time:%VCPKG_BOOST_PLATFORM% boost-filesystem:%VCPKG_BOOST_PLATFORM% boost-interprocess:%VCPKG_BOOST_PLATFORM% boost-intrusive:%VCPKG_BOOST_PLATFORM% boost-lexical-cast:%VCPKG_BOOST_PLATFORM% boost-locale:%VCPKG_BOOST_PLATFORM% boost-mpl:%VCPKG_BOOST_PLATFORM% boost-optional:%VCPKG_BOOST_PLATFORM% boost-range:%VCPKG_BOOST_PLATFORM% boost-thread:%VCPKG_BOOST_PLATFORM% boost-type-traits:%VCPKG_BOOST_PLATFORM% boost-units:%VCPKG_BOOST_PLATFORM% boost-utility:%VCPKG_BOOST_PLATFORM% boost-variant:%VCPKG_BOOST_PLATFORM% boost-program-options:%VCPKG_BOOST_PLATFORM%
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))



build_script:
- cmd: >-
    call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\%VCVARS%.bat" &&
    cmake -GNinja -Bbuild -H. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:/Python37-x64/python.exe -DCMAKE_PREFIX_PATH=C:/Libraries/boost_%BOOST_VER%;C:/Tools/vcpkg/installed/%VCPKG_PLATFORM%;C:/projects -DVCPKG_TARGET_TRIPLET=%VCPKG_PLATFORM% &&
    ninja -C build
