component_depth: 3
languages:
- cpp
exclude:
- /apps/.*
- /assets/.*
- /cmake/.*
- /cmake-local/.*
- /devtools/.*
- /doc/.*
- /doc-internal/.*
- /examples/.*
- /inc/.*
- /json-schemas/.*
- /plugins/.*
- /vendor/.*
