/** @file
    @brief Header containing simple traits definitions.

    While this file contains all of the main traits generated by macros, it is
   suggested that you include the specific header file for the trait you want to
   use, in case the structure changes and to make the include list more
   semantic.

    @date 2014

    @author
    Sensics, Inc.
    <http://sensics.com/osvr>
*/

// Copyright 2014 Sensics, Inc.
//
// All rights reserved.
//
// (Final version intended to be licensed under
// the Apache License, Version 2.0)

#ifndef INCLUDED_ReportTraits_h_GUID_CEDB196C_04E8_4085_EDCF_C5A1BD81A827
#define INCLUDED_ReportTraits_h_GUID_CEDB196C_04E8_4085_EDCF_C5A1BD81A827

// Internal Includes
#include <osvr/Util/ClientCallbackTypesC.h>

// Library/third-party includes
// - none

// Standard includes
// - none

namespace osvr {
namespace client {
    namespace traits {
        /// @brief Metafunction taking a ReportType and returning the associated
        /// CallbackType
        /// @headerfile CallbackType.h <osvr/Client/CallbackType.h>
        template <typename T> struct CallbackType {};

        /** @brief Metafunction taking a CallbackType and returning the
        associated ReportType
        @headerfile ReportFromCallback.h <osvr/Client/ReportFromCallback.h>
        */
        template <typename T> struct ReportFromCallback {};

        /// @brief Metafunction taking a ReportType and returning the associated
        /// StateType
        /// @headerfile StateType.h <osvr/Client/StateType.h>
        template <typename T> struct StateType {};

#define OSVR_REPORT_TRAITS(TYPE)                                               \
    template <> struct CallbackType<OSVR_##TYPE##Report> {                     \
        typedef OSVR_##TYPE##Callback type;                                    \
    };                                                                         \
    template <> struct ReportFromCallback<OSVR_##TYPE##Callback> {             \
        typedef OSVR_##TYPE##Report type;                                      \
    };                                                                         \
    template <> struct StateType<OSVR_##TYPE##Report> {                        \
        typedef OSVR_##TYPE##State type;                                       \
    };
        OSVR_REPORT_TRAITS(Analog)
        OSVR_REPORT_TRAITS(Button)
        OSVR_REPORT_TRAITS(Pose)
        OSVR_REPORT_TRAITS(Position)
        OSVR_REPORT_TRAITS(Orientation)
        OSVR_REPORT_TRAITS(Imaging)
#undef OSVR_REPORT_TRAITS
    } // namespace traits

} // namespace client
} // namespace osvr

#endif // INCLUDED_ReportTraits_h_GUID_CEDB196C_04E8_4085_EDCF_C5A1BD81A827
